### ISSUE TITLE
Plugin not working in IntelliJ 14.1 EAP

### ISSUE THREAD

**Issue by palloberg** [mjedynak/EqualsHashCodeDeluxeGenerator#21]
In the pre-releases (EAP) of IntelliJ 14.1 Community Editition the plugin is no longer working and throws an exception when attempting to generate the code.

https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP

```
com.intellij.codeInsight.generation.GenerateEqualsHelper.isNestedArray(Lcom/intellij/psi/PsiType;)Z
java.lang.NoSuchMethodError: com.intellij.codeInsight.generation.GenerateEqualsHelper.isNestedArray(Lcom/intellij/psi/PsiType;)Z
	at pl.mjedynak.idea.plugins.wizard.GenerateEqualsHashCodeDeluxeWizard$EqualsMemberInfoModel.isMemberEnabled(GenerateEqualsHashCodeDeluxeWizard.java:294)
	at pl.mjedynak.idea.plugins.wizard.GenerateEqualsHashCodeDeluxeWizard$EqualsMemberInfoModel.isMemberEnabled(GenerateEqualsHashCodeDeluxeWizard.java:274)
	at com.intellij.refactoring.ui.AbstractMemberSelectionTable.isMemberInfoSelected(AbstractMemberSelectionTable.java:113)
	at com.intellij.refactoring.ui.AbstractMemberSelectionTable.scrollSelectionInView(AbstractMemberSelectionTable.java:171)
	at com.intellij.refactoring.ui.AbstractMemberSelectionTable.addNotify(AbstractMemberSelectionTable.java:182)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at java.awt.Container.addNotify(Container.java:2769)
	at javax.swing.JComponent.addNotify(JComponent.java:4753)
	at javax.swing.JRootPane.addNotify(JRootPane.java:756)
	at java.awt.Container.addNotify(Container.java:2769)
	at java.awt.Window.addNotify(Window.java:770)
	at java.awt.Dialog.addNotify(Dialog.java:760)
	at java.awt.Window.pack(Window.java:807)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:667)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.openapi.ui.DialogWrapper$show.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at pl.mjedynak.idea.plugins.action.GenerateEqualsHashCodeDeluxeActionHandler.chooseOriginalMembers(GenerateEqualsHashCodeDeluxeActionHandler.groovy:97)
	at com.intellij.codeInsight.generation.GenerateMembersHandlerBase.invoke(GenerateMembersHandlerBase.java:76)
	at com.intellij.codeInsight.actions.CodeInsightAction$1$1.run(CodeInsightAction.java:62)
	at com.intellij.codeInsight.actions.CodeInsightAction$1.run(CodeInsightAction.java:69)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:54)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by palloberg** [comment]
It appears the isNestedArray method was moved into `org.jetbrains.java.generate.psi.PsiAdapter` in this commit:
https://github.com/JetBrains/intellij-community/commit/0ee564a95ef64ce74ea4d26084da9086198dbe68

**Comment by tomjankes** [comment]
I can confirm this on (now released) Intellij Idea 14.1 Community Edition.

**Comment by mjedynak** [comment]
Fixed in 1.0.12
